# Generated by Django 5.1.3 on 2025-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Picture'),
        ),
    ]
