# Generated by Django 5.1.3 on 2025-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_remove_user_mobile_user_avator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Picture'),
        ),
    ]
