# Generated by Django 5.1.3 on 2024-12-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='title')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='title on url ')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('short_desc', models.CharField(db_index=True, max_length=400, verbose_name='Short Description')),
                ('main_desc', models.TextField(db_index=True, verbose_name='Main Description')),
                ('is_active', models.BooleanField(verbose_name='active / deactive')),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
                ('is_delete', models.BooleanField(verbose_name='Deleted / Not')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='tag')),
                ('is_active', models.BooleanField(verbose_name='active / deactive')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product_module.product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
            },
        ),
    ]
