# Generated by Django 5.1.3 on 2025-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productcategory_is_active_productcategory_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=200, verbose_name='Url Name'),
            preserve_default=False,
        ),
    ]
