# Generated by Django 5.1.3 on 2025-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='About Us')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fax')),
                ('copy_right', models.CharField(blank=True, max_length=400, null=True, verbose_name='Copy Right Text')),
                ('site_logo', models.ImageField(upload_to='images/site-settings/', verbose_name='Logo')),
                ('is_main_setting', models.BooleanField(verbose_name='Main Setting')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
