# Generated by Django 5.1.3 on 2025-01-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.URLField(max_length=500, verbose_name='Url')),
                ('url_title', models.CharField(max_length=200, verbose_name='Url title')),
                ('disc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/sliders/', verbose_name='Picture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active/deactive')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
