# Generated by Django 5.1.3 on 2025-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.URLField(max_length=400, verbose_name='Banner URL')),
                ('image', models.ImageField(upload_to='images/banners/', verbose_name='Picture')),
                ('position', models.CharField(choices=[('home_page', 'Main Page'), ('product_list', 'Product List Page'), ('product_detail', 'Product Detail Page')], max_length=300, verbose_name='Ad Banners')),
            ],
            options={
                'verbose_name': 'Ad Banner',
                'verbose_name_plural': 'Ad Banners',
            },
        ),
    ]
