# Generated by Django 5.1.3 on 2024-12-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('full_name', models.CharField(max_length=300, verbose_name='Full Name')),
                ('message', models.TextField(verbose_name='Text')),
                ('is_read_by_admin', models.BooleanField(verbose_name='Read by Admin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response text with us')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact us list',
            },
        ),
    ]
