# Generated by Django 5.1.3 on 2025-01-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title of category')),
                ('url_title', models.CharField(max_length=400, unique=True, verbose_name='Title of Url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable/Disable')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title of Article')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='Title of Url')),
                ('image', models.ImageField(upload_to='images/articles/', verbose_name='Picture')),
                ('short_desc', models.TextField(verbose_name='Short Description')),
                ('text', models.TextField(verbose_name='Text of article')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enable/Disable')),
                ('selected_categories', models.ManyToManyField(to='article_module.articlecategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
